### ISSUE TITLE
Gradient line code to for Edit mode

### ISSUE THREAD

**Issue by DutchPete** [mimishahzad/rose-pine-moon-obsidian#2]
Hi, I like the rainbow horizontal gradient line. I would like to have it rendered as such in Edit mode too. I have this:

```css
.cm-s-obsidian .HyperMD-hr {
  border: 0 !important;
  height: 0.35rem;
  width: 100%;
  position: relative;
  display: block;
  background-image: -webkit-linear-gradient(
    0deg,
    transparent,
    #f6c177,
    #eb6f92,
    #ea9a97,
    #C5A3FF,
    #9ccfd8,
    transparent
  ) !important;
  clear: both;
}
```

but that still leaves an ugly black line running through it:

![image](https://user-images.githubusercontent.com/10794265/138599185-257e8f70-ddac-41d1-aa39-5635c984f7a8.png)

Any suggestions?
